"use client";
import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";
import Link from "next/link";
import { usePathname } from "next/navigation";

const manrope = Manrope({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();
  return (
    <html lang="en">
      <body className={manrope.className}>
        <>
          <Navbar />
          {/* <Toaster /> */}
          <div className="flex flex-col lg:flex-row py-8 px-[8.25%] bg-gray-50 dark:bg-gray-950 gap-8">
            <div className="w-56 flex flex-col gap-4">
              <div className="grow flex flex-col gap-5 px-6 py-6 rounded-3xl shadow-sm bg-white dark:bg-gray-900">
                {[
                  "orders",
                  "products",
                  "categories",
                  "subcategories",
                  "coupons",
                  "carousel",
                  "blogs",
                ].map((route) => {
                  return (
                    <Link href={"/" + route}>
                      <p>{route}</p>
                    </Link>
                  );
                })}
              </div>
            </div>
            <div className="grow">
              <h2 className="text-4xl font-semibold mb-8 soyuz-grotesk">
                {path.replace("/", "").replaceAll("-", " ")}
              </h2>
              <div className="px-4 md:px-8 py-8 rounded-2xl md:rounded-3xl shadow-sm bg-white dark:bg-gray-900">
                {children}
              </div>
            </div>
          </div>
          <Footer />
        </>
      </body>
    </html>
  );
}
